name: Update GitHub Stats

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  update-readme:
    name: Update GitHub Profile README
    runs-on: ubuntu-latest
    steps:
      # Check out your repository
      - uses: actions/checkout@v3
      
      # Update Recent Activity Section
      - name: Update Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update GitHub activity'
          MAX_LINES: 5
      
      # Optional: Update GitHub metrics (if you want to add more statistics)
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lenkalapellypraveen
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          
      # Commit and push if there are changes
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub stats"
          git push
