name: Update GitHub Stats

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  update-readme:
    name: Update GitHub Profile README
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write permission
    steps:
      # Check out your repository with token
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      # Update Recent Activity Section
      - name: Update Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update GitHub activity'
          MAX_LINES: 5
          
      # Commit and push if there are changes
      - name: Commit changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update GitHub stats"
          git push
